services:
  pgserver:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - data:/var/lib/postgresql
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.de
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - "8080:80"
    depends_on:
      - pgserver

volumes:
  data: {}
